### PR TITLE
Include acmart-options to allow for more detailed configuration

### PR DESCRIPTION
**Pull request by AlarithUhde**
Adds acmart-options as suggested here:

https://github.com/quarto-journals/acm/issues/11#issuecomment-1380729545

This allows the author to configure the article options, for example to switch from the manuscript to sigconf layout or add/remove line numbers.

This also adds a comment in the quarto template with an example to use the options

### CODE REVIEW

**Comment by cscheid** [comment]
Thank you, this is very helpful. I was going to make the change myself.

Have you filed a [contributor agreement](https://github.com/quarto-dev/quarto-cli/blob/main/CONTRIBUTING.md) with us? I think we'll need one of those before we take your change.

**Comment by AlarithUhde** [comment]
Oh, I'm sorry, I was not aware of this. Maybe it would be easiest to take back my pull request here, given that you wrote the code in the first place?

**Comment by cscheid** [comment]
Yeah, that's totally fine with me as well. I just didn't want to let your generosity go unnoticed.

**Comment by cscheid** [comment]
I just pushed these changes to main myself. Thank you for the suggestion and feedback!

**Pull request closed without merging**
